# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sledge-Plugin-DebugScreen
version:      0.05
version_from: lib/Sledge/Plugin/DebugScreen.pm
installdirs:  site
requires:
    Devel::StackTrace:             1.12
    IO::File:                      1.1
    Template:                      2.14
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
